//
// Created by jiangeng on 10/18/19.
//

#ifndef ATLASMPNET_CMAKE_CONFIG_H
#define ATLASMPNET_CMAKE_CONFIG_H

#ifdef ATLASMPNET_DEBUG
#define ATLASMPNET_DEBUGLEVEL 4
#else
#define ATLASMPNET_DEBUGLEVEL 3
#endif

#endif //ATLASMPNET_CMAKE_CONFIG_H
